# Generated by Django 5.2 on 2025-06-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('semester', models.PositiveSmallIntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
