# Generated by Django 5.2 on 2025-06-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_teacher_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, unique=True)),
                ('num_co_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
