# Generated by Django 5.2 on 2025-06-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_numberofco_alter_teacher_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberofco',
            name='id',
        ),
        migrations.AlterField(
            model_name='numberofco',
            name='subject_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
