# Generated by Django 5.2 on 2025-06-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
