# Generated by Django 5.2 on 2025-06-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_id_alter_marks_roll_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='IA1_1a_co_lvl',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='IA1_1b_co_lvl',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='IA1_2a_co_lvl',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='IA1_2b_co_lvl',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='IA2_1a_co_lvl',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='IA2_1b_co_lvl',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='IA2_2a_co_lvl',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='IA2_2b_co_lvl',
        ),
    ]
